[package]
name = "fastsegy"
version = "0.1.0"
edition = "2024"

[lib]
name = "_fastsegy"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
ebcdic = "0.1.2"
numpy = "0.27.1"